app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
  termsOfServiceUrl: http://www.github.com/jntakpe/skillmatcher
  contact: j.ntakpe@gmail.com
  license: MIT
  licenseUrl: http://opensource.org/licenses/MIT
management:
  context-path: /manage
  security:
    enabled: false
spring:
  jpa:
    openInView: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.format_sql: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
authentication:
    oauth:
        clientId: skillmatcher
        secret: skillmatchersupersecuresecret
        tokenValidityInSeconds: 1800
---
spring:
  profiles: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    database: postgresql
datasource:
  url: jdbc:postgresql://localhost:5432/skillmatcher
  username: postgres
  password: sopra*
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
